orbs:
  aws-eks: circleci/aws-eks@0.2.1
  aws-cli: circleci/aws-cli@0.1.19
  helm: circleci/helm@0.2.3
  slack: circleci/slack@3.4.0
  jq: circleci/jq@1.9.0

version: 2.1
jobs:
  build-image:
    executor: aws-cli/default
    environment:
      - DOCKER_REPO: mouwang
      - DOCKER_IMAGE: m1ga
      - CLUSTER_NAME: mouworks-cluster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Hub Login
          command: echo "${DOCKER_PASS}" | docker login --username ${DOCKER_USER} --password-stdin
      - run:
          name: Check Docker Version
          command: docker -v
      - run:
          name: Move to Build Folder && Build
          command: |
            docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE}:1.0.${CIRCLE_BUILD_NUM} .
      - run:
          name: Push to Docker Hub
          command: docker push ${DOCKER_REPO}/${DOCKER_IMAGE}:1.0.${CIRCLE_BUILD_NUM}
  helm-deploy:
    executor: aws-eks/python
    parameters:
      cluster-name:
        description: mouworks-cluster
        type: string
    steps:
      - helm/install-helm-client:
          version: v3.0.0
      - run:
          name: helm repo
          command: helm repo add stable https://kubernetes-charts.storage.googleapis.com/
      - aws-cli/setup
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - run:
          name: Where Am I ?
          command: pwd
      - run:
          name: list files
          command: ls
      - helm/upgrade-helm-chart:
          release-name: m1ga
          chart: "helmChart"
          version: 1.0.${CIRCLE_BUILD_NUM}
#          values-to-override: appVersion=1.0.${CIRCLE_BUILD_NUM}
workflows:
  version: 2.1
  deployment:
    jobs:
      - build-image
      - helm-deploy:
          cluster-name: mouworks-cluster
          requires:
            - build-image


