{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "m1ga.serviceAccountName" . }}
  labels:
{{ include "m1ga.labels" . | nindent 4 }}
{{- end -}}
